export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const DEACTIVATE_CATEGORY = "DEACTIVATE_CATEGORY";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const FETCH_CATEGORY_FAILED = "FETCH_CATEGORY_FAILED";

export const PURCHASE_PRODUCT_SUCCESS = "PURCHASE_PRODUCT_SUCCESS";
export const PURCHASE_PRODUCT_FAIL = "PURCHASE_PRODUCT_FAIL";
export const PURCHASE_PRODUCT_START = "PURCHASE_PRODUCT_START";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS_START = "FETCH_ORDER_START";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDERS_FAIL = "FETCH_ORDER_FAIL";
